products = [
  {
    "id": 1,
    "name": "NIKE ZOOM MERCURIAL VAPOR 15 ELITE CR7 FG SOCCER CLEATS",
    "image": "../image/NIKE-ZOOM-MERCURIAL-VAPOR-15-ELITE.png",
    "description": "Nike shoes to feel like Cristinao Ronaldo",
    "brand": "Nike",
    "category": "Soccer shoes",
    "price": 259.99,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "id": 2,
    "name": "PUMA X PULISIC ULTRA ULTIMATE FG/AG SOCCER CLEATS",
    'image': "../image/PUMA-X-PULISIC-ULTRA-ULTIMATE.png",
    'description': "The newest shoes from Puma",
    "brand": "Puma",
    "category": "Soccer shoes",
    "price": 210.0,
    "countInStock": 10,
    "rating": 4.0,
    "numReviews": 8,
  },
  {
    "id": 3,
    "name": "ADIDAS FIFA WORLD CUP AL RIHLA PRO OFFICIAL MATCH SOCCER BALL",
    "image": "../image/adidasBall.png",
    "description": "Adida ball World Cup 2023",
    "brand": "Adidas",
    "category": "Ball",
    "price": 59.99,
    "countInStock": 5,
    "rating": 3,
    "numReviews": 12,
  },
  {
    "id": 4,
    "name": "DIADORA BRASIL ELITE2 TECH ITALIA LPX FG SOCCER CLEATS",
    "image": "../image/Diadora.png",
    "description": "The famous shoes from Diadora",
    "brand": "Diadora",
    "category": "Soccer shoes",
    "price": 200.99,
    "countInStock": 11,
    "rating": 5,
    "numReviews": 12,
  },
  {
    "id": 5,
    "name": "NIKE PREMIER LEAGUE FLIGHT SOCCER BALL",
    "image": "../image/PrimerLigeBall.png",
    "description": "PrimerLige Ball",
    "brand": "Nike",
    "category": "Ball",
    "price": 49.99,
    "countInStock": 7,
    "rating": 3.5,
    "numReviews": 10,
  },
  {
    "id": 6,
    "name": "NEW BALANCE TEKELA V4 PRO FG SOCCER CLEATS",
    "image": "../image/NEW BALANCE TEKELA V4 PRO FG SOCCER CLEATS.png",
    "description": "New Balance shoes from collection 2023",
    "brand": "New Balance",
    "category": "Soccer shoes",
    "price": 193.59,
    "countInStock": 0,
    "rating": 4,
    "numReviews": 12,
  },
  {
    "id": 7,
    "name": "NEW BALANCE TEKELA V4 PRO FG SOCCER CLEATS",
    "image": "../image/NEW BALANCE TEKELA V4 PRO FG SOCCER CLEATS.png",
    "description": "New Balance shoes from collection 2023",
    "brand": "New Balance",
    "category": "Soccer shoes",
    "price": 193.59,
    "countInStock": 0,
    "rating": 4,
    "numReviews": 12,
  },
 
]
