# Generated by Django 4.1.5 on 2023-02-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_create_order_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
