# Generated by Django 4.1.5 on 2023-02-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
    ]
